### ISSUE TITLE
datagridItem.downloadFilePath is undefined when publishing multiple items

### ISSUE THREAD

**Issue by serkanserttop** [SmartfaceIO/smartface.publish.wizard#1]
Below `datagridItem.downloadFilePath` is undefined in `response.responseDone` case.
Most likely, `response.downloadFilePath` case is never sent after the first item.

			} else if (response.downloadFilePath) {
				datagridItem.downloadFilePath = response.downloadFilePath;
			} else if (response.responseDone) {
				var c9path = datagridItem.downloadFilePath.replace(c9.workspaceDir, '');

**Comment by alperozisik** [comment]
using different item now
