### ISSUE TITLE
Publish screen problem when there is an invalid project.json

### ISSUE THREAD

**Issue by mrvbicakci** [SmartfaceIO/smartface.publish.wizard#2]
If I try to get iOS publish with an invalid project.json, it gives an error, this is ok.

![invalidprojectjson](https://cloud.githubusercontent.com/assets/12133528/12448751/deccbc48-bf80-11e5-86d4-1d1be3df8137.PNG)

But then if I want to get publish again, publish screen is not available for use. I cannot select iOS or Android (iOS seems selected).

**Comment by alperozisik** [comment]
Error checks implemented
