### ISSUE TITLE
Android plugin path

### ISSUE THREAD

**Issue by mrvbicakci** [SmartfaceIO/smartface.publish.wizard#3]
I tried to use 

   "plugins" : {
     	"smfimagecode" : {
	     	"path" : "plugins/Android/CodeReaderAndroid.zip",
		     "active" : true
	    }
     }

for android plugin path.

I put CodeReaderAndroid.zip plugin under plugins folder.
I tried to get publish, it gave an error as in the attachment:

![androidpluginpath](https://cloud.githubusercontent.com/assets/12133528/12451123/34a235bc-bf90-11e5-8e6c-5d9eb1f605b5.PNG)

After that, I closed publish screen, and tried to publish again, but I couldn't. It seems that publish is still running, but there was no output.
![androidpluginpath2](https://cloud.githubusercontent.com/assets/12133528/12451163/6652f3c6-bf90-11e5-9542-9a8e6fd50a98.PNG)

**Comment by alperozisik** [comment]
done
